# Generated by Django 3.1.1 on 2020-09-03 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200724_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 24, 38, 671138)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 24, 38, 671522)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='timestamp_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 24, 38, 670574)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
